### ISSUE TITLE
cancelAutoFocus failed

### ISSUE THREAD

**Issue by sibelius** [react-native-community/react-native-camera#1087]
It looks like something cancelAutoFocus can fail, so we need to make this more robust: 

```jsx
Fatal Exception: java.lang.RuntimeException: cancelAutoFocus failed
       at android.hardware.Camera.native_cancelAutoFocus(Camera.java)
       at android.hardware.Camera.cancelAutoFocus(Camera.java:1326)
       at com.lwansbrough.RCTCamera.RCTCameraViewFinder.handleFocus(RCTCameraViewFinder.java:420)
       at com.lwansbrough.RCTCamera.RCTCameraViewFinder.onTouchEvent(RCTCameraViewFinder.java:378)
       at android.view.View.dispatchTouchEvent(View.java:10026)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2635)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2635)
```

related to https://github.com/react-native-community/react-native-camera/issues/1038 and https://github.com/react-native-community/react-native-camera/issues/992

**Comment by sibelius** [comment]
RCTCamera is removed https://github.com/react-native-community/react-native-camera/issues/1890

Migrate to latest version of RNCamera
