### ISSUE TITLE
Media recorder error (android only)

### ISSUE THREAD

**Issue by cainaleaouk** [react-native-community/react-native-camera#1186]
### Which implementation are you using

RCTCamera or RNCamera?
`RCTCamera`

### Steps to reproduce
1. Component 1 use `<Camera/>` take a picture or record a video
2. Component 1 calls component 2
3. Component 2 use `<Camera/>` take a picture or record a video

### Expected behaviour
(This works on iOS) : Take a picture (or record a video), then successfully take a picture (or record a video) with no problems in the next component

### Actual behaviour
App crash with the current log:
```
01-31 13:10:15.177 30716-30716/com.skeletonapp E/MediaRecorder: start failed: -38
01-31 13:10:15.197 30716-30716/com.skeletonapp E/RCTCameraModule: Media recorder start error.
                                                                  java.lang.IllegalStateException
                                                                      at android.media.MediaRecorder.start(Native Method)
                                                                      at com.lwansbrough.RCTCamera.RCTCameraModule.record(RCTCameraModule.java:357)
                                                                      at com.lwansbrough.RCTCamera.RCTCameraModule.captureWithOrientation(RCTCameraModule.java:514)
                                                                      at com.lwansbrough.RCTCamera.RCTCameraModule.access$100(RCTCameraModule.java:38)
                                                                      at com.lwansbrough.RCTCamera.RCTCameraModule$2.orientationEvent(RCTCameraModule.java:498)
                                                                      at com.lwansbrough.RCTCamera.RCTSensorOrientationChecker$Listener.onSensorChanged(RCTSensorOrientationChecker.java:64)
                                                                      at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:630)
                                                                      at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                      at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                      at android.os.Looper.loop(Looper.java:138)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5454)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-31 13:10:15.207 30716-30758/com.skeletonapp E/ReactNativeJS: { [Error: null] framesToPop: 1, code: 'EUNSPECIFIED' }
```

### Observation
Initially I thought the problem had to do with video recording, because I take a picture in the first component (for profile) then the next component records a video of the player interacting with the application, which made the app on Android crash. I tried then changing the first component to record videos and it worked just fine. Then I changed the second component to take a picture instead of video and the same crash happened.

### Environment
- **Node.js version**: `6.9.5`
- **React Native version**: `0.50.3`
- **React Native platform + platform version**: `Android 6.0.1`

### react-native-camera
**Version**: `^0.13.0`

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by sibelius** [comment]
RCTCamera is removed https://github.com/react-native-community/react-native-camera/issues/1890

Migrate to latest version of RNCamera
