### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid image data size.

### ISSUE THREAD

**Issue by sibelius** [react-native-community/react-native-camera#1255]
```
Caused by java.lang.IllegalArgumentException: Invalid image data size.
       at com.google.android.gms.vision.Frame$Builder.setImageData(Unknown Source)
       at org.reactnative.facedetector.RNFrameFactory.buildFrame(RNFrameFactory.java:16)
       at org.reactnative.camera.tasks.FaceDetectorAsyncTask.doInBackground(FaceDetectorAsyncTask.java:40)
       at org.reactnative.camera.tasks.FaceDetectorAsyncTask.doInBackground(FaceDetectorAsyncTask.java:10)
       at android.os.AsyncTask$2.call(AsyncTask.java:305)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```

**Comment by wcandillon** [comment]
@sibelius We might be experiencing the same issue, did you find a fix/workaround for it?

**Comment by andreseiji** [comment]
```
Caused by: java.lang.IllegalArgumentException: Invalid image data size.
        at com.google.android.gms.vision.Frame$Builder.setImageData(Unkno
        at com.google.firebase.ml.vision.common.FirebaseVisionImage.zza(U
        at com.google.android.gms.internal.firebase_ml.zzpw.zza(Unknown S
        at com.google.firebase.ml.vision.face.FirebaseVisionFaceDetector.Unknown Source)
        at org.reactnative.camera.tasks.ResolveTakenPictureAsyncTask.doInolveTakenPictureAsyncTask.java:109)
        at org.reactnative.camera.tasks.ResolveTakenPictureAsyncTask.doInolveTakenPictureAsyncTask.java:37)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
```

**Comment by sibelius** [comment]
for the fix follow this https://github.com/expo/expo/pull/2772

**Comment by MateusAndrade** [comment]
> for the fix follow this [expo/expo#2772](https://github.com/expo/expo/pull/2772)

i can pick this

**Comment by MateusAndrade** [comment]
This still happens? I gave a look at ```FaceDetectorAsyncTask``` and there is already a treatment to this:

```java
  @Override
  protected SparseArray<Face> doInBackground(Void... ignored) {
    if (isCancelled() || mDelegate == null || mFaceDetector == null || !mFaceDetector.isOperational()) {
      return null;
    }

    RNFrame frame = RNFrameFactory.buildFrame(mImageData, mWidth, mHeight, mRotation);
    return mFaceDetector.detect(frame);
  }
```

@sibelius do you think wrapping ```doInBackground``` with a try catch is a good addition? Btw, this method is implemented on 11 files with some differences.

What did you do to catch this error?

**Comment by sibelius** [comment]
check the expo PR

it is about `BarCodeScannerResult`, not face detection

**Comment by sibelius** [comment]
nevermind, the errortrack is on face detector as well

a try catch could help on this one
