### ISSUE TITLE
RNCamera Camera 2 bug

### ISSUE THREAD

**Issue by sibelius** [react-native-community/react-native-camera#1308]
![image](https://user-images.githubusercontent.com/2005841/36863084-78dbb186-1d67-11e8-9114-e57fe54c1ca9.png)

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.hardware.camera2.CameraCaptureSession.capture(android.hardware.camera2.CaptureRequest, android.hardware.camera2.CameraCaptureSession$CaptureCallback, android.os.Handler)' on a null object reference
       at com.google.android.cameraview.Camera2.unlockFocus(Camera2.java:1082)
       at com.google.android.cameraview.Camera2$8.onCaptureCompleted(Camera2.java:993)
       at java.lang.reflect.Method.invoke(Method.java)
       at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
       at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7409)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by jgfidelis** [comment]
since camera2 is not the default anymore, this bug may be solved :trollface:
