### ISSUE TITLE
react-native-camera record video crashes while capturing video

### ISSUE THREAD

**Issue by RCTnativeapp** [react-native-community/react-native-camera#1337]
Hi, I am using in reactnative for recording video. It works in iOS and but not in Android
"react-native-camera": "^0.12.0",

When I start recoding video, from camera while capturing the timer, app crashes
Please help.
```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                                      java.lang.RuntimeException: Error retrieving camcorder profile params
                                                       at android.media.CamcorderProfile.native_get_camcorder_profile(Native Method)
                                                       at android.media.CamcorderProfile.get(CamcorderProfile.java:402)
                                                       at com.lwansbrough.RCTCamera.RCTCamera.setCaptureVideoQuality(RCTCamera.java:278)
                                                       at com.lwansbrough.RCTCamera.RCTCameraModule.prepareMediaRecorder(RCTCameraModule.java:264)
                                                       at com.lwansbrough.RCTCamera.RCTCameraModule.record(RCTCameraModule.java:350)
                                                       at com.lwansbrough.RCTCamera.RCTCameraModule.captureWithOrientation(RCTCameraModule.java:514)
                                                       at com.lwansbrough.RCTCamera.RCTCameraModule.access$100(RCTCameraModule.java:38)
                                                       at com.lwansbrough.RCTCamera.RCTCameraModule$2.orientationEvent(RCTCameraModule.java:498)
                                                       at com.lwansbrough.RCTCamera.RCTSensorOrientationChecker$Listener.onSensorChanged(RCTSensorOrientationChecker.java:64)
                                                       at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:481)
                                                       at android.os.MessageQueue.nativePollOnce(Native Method)
                                                       at android.os.MessageQueue.next(MessageQueue.java:328)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5728)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```
[crashlog.txt](https://github.com/react-native-community/react-native-camera/files/1798368/crashlog.txt)

Thanks,
Sipra

**Comment by jgfidelis** [comment]
try to update your package to 1.0.1 and use RNCamera

**Comment by RCTnativeapp** [comment]
Thanks. will update the package.

Any clue on below error while recording video:
 startCopy UserHandle{0}: MeasureParams{e370b50 com.android.soundrecorder}
03-09 16:22:13.918 7275-7275/? E/AEE/DUMPSTATE: copy_file: Copy /sys/kernel/debug/page_recorder/Usage_rank to SYS_PAGE_RECORDER failed(2), No such file or directory

**Comment by fazeelzama20** [comment]
When I start video recording then this error occurred.
Error: start failed.
    at createErrorFromErrorData (index.bundle:1807)
    at index.bundle:1760
    at MessageQueue.__invokeCallback (index.bundle:2118)
    at index.bundle:1935
    at MessageQueue.__guard (index.bundle:2053)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (index.bundle:1934)
    at debuggerWorker.js:72

**Comment by ChristineTzeng** [comment]
Does that mean the video recording feature for RCTCamera doesn't work anymore?

**Comment by coryarmbrecht** [comment]
I'm hitting the same issue, but I don't get any error output.

**Comment by SimonErm** [comment]
https://github.com/react-native-community/react-native-camera/pull/1835
