### ISSUE TITLE
Chinese phones can not use google so app will crash

### ISSUE THREAD

**Issue by Eggplant-Cui** [react-native-community/react-native-camera#1505]
### Warning
RCTCamera is **DEPRECATED** on v1.0.0 follow our migration guide here https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md

### Which implementation are you using

RNCamera

### Steps to reproduce
RNCameraView.<init>

### Expected behaviour
Not crash, maybe add a switch for Chinese developers will help a lot.

My device: Mi6 
Here is the log.
04-21 18:21:02.621 27816-27816/com.shuipingyi E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.shuipingyi, PID: 27816
                                                                java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzdls;
                                                                    at com.google.android.gms.vision.text.TextRecognizer$Builder.<init>(Unknown Source:5)
                                                                    at org.reactnative.camera.RNCameraView.<init>(RNCameraView.java:83)
                                                                    at org.reactnative.camera.CameraViewManager.createViewInstance(CameraViewManager.java:53)
                                                                    at org.reactnative.camera.CameraViewManager.createViewInstance(CameraViewManager.java:16)
                                                                    at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
                                                                    at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:224)
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:153)
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:816)
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:929)
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:47)
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:989)
                                                                    at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
                                                                    at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
                                                                    at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:780)
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:712)
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:954)
                                                                    at android.os.Handler.handleCallback(Handler.java:789)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                    at android.os.Looper.loop(Looper.java:164)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6665)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
                                                                 Caused by: java.lang.ClassNotFoundException: com.google.android.gms.internal.zzdls
                                                                    at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                    at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                    at com.google.android.gms.vision.text.TextRecognizer$Builder.<init>(Unknown Source:5) 
                                                                    at org.reactnative.camera.RNCameraView.<init>(RNCameraView.java:83) 
                                                                    at org.reactnative.camera.CameraViewManager.createViewInstance(CameraViewManager.java:53) 
                                                                    at org.reactnative.camera.CameraViewManager.createViewInstance(CameraViewManager.java:16) 
                                                                    at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44) 
                                                                    at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:224) 
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:153) 
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:816) 
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:929) 
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:47) 
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:989) 
                                                                    at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31) 
                                                                    at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136) 
                                                                    at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107) 
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966) 
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:780) 
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:712) 
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:954) 
                                                                    at android.os.Handler.handleCallback(Handler.java:789) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                    at android.os.Looper.loop(Looper.java:164) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6665) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781) 
                                                                 Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbgl;
                                                                    at com.google.android.gms.vision.text.TextRecognizer$Builder.<init>(Unknown Source:5) 
                                                                    at org.reactnative.camera.RNCameraView.<init>(RNCameraView.java:83) 
                                                                    at org.reactnative.camera.CameraViewManager.createViewInstance(CameraViewManager.java:53) 
                                                                    at org.reactnative.camera.CameraViewManager.createViewInstance(CameraViewManager.java:16) 
                                                                    at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44) 
                                                                    at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:224) 
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:153) 
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:816) 
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:929) 
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:47) 
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:989) 
                                                                    at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31) 
                                                                    at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136) 
                                                                    at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107) 
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966) 
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:780) 
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:712) 
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:954) 
                                                                    at android.os.Handler.handleCallback(Handler.java:789) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                    at android.os.Looper.loop(Looper.java:164) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6665) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781) 
                                                                 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzbgl" on path: DexPathList[[zip file "/data/app/com.shuipingyi-MJqPWEG90n1I39D5kKvHFg==/base.apk"],nativeLibraryDirectories=[/data/app/com.shuipingyi-MJqPWEG90n1I39D5kKvHFg==/lib/arm, /system/fake-libs, /data/app/com.shuipingyi-MJqPWEG90n1I39D5kKvHFg==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
                                                                    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                    at com.google.android.gms.vision.text.TextRecognizer$Builder.<init>(Unknown Source:5) 
                                                                    at org.reactnative.camera.RNCameraView.<init>(RNCameraView.java:83) 
                                                                    at org.reactnative.camera.CameraViewManager.createViewInstance(CameraViewManager.java:53) 
                                                                    at org.reactnative.camera.CameraViewManager.createViewInstance(CameraViewManager.java:16) 
                                                                    at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44) 
                                                                    at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:224) 
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:153) 
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:816) 
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:929) 
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:47) 
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:989) 
                                                                    at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31) 
                                                                    at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136) 
                                                                    at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107) 
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966) 
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:780) 
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:712) 
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:954) 
                                                                    at android.os.Handler.handleCallback(Handler.java:789) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                    at android.os.Looper.loop(Looper.java:164) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6665) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**Comment by jgfidelis** [comment]
Can you explain the title better?

**Comment by cookorg** [comment]
我也是这么认为,在中国的手机默认没有google-play-services，很遗憾啊

**Comment by pbmlly** [comment]
有什么替代方案吗？我最近也遇到这个问题了。

**Comment by sibelius** [comment]
RCTCamera is removed https://github.com/react-native-community/react-native-camera/issues/1890

Migrate to latest version of RNCamera

**Comment by yylingsj** [comment]
@sibelius 从3.43.x版本开始一直尝试，到现在的最新版3.44.1了，TextRecogized特性在安卓手机上依然会闪退，React Native使用的最新版0.64，iOS可以正常使用这个特性，无解了，还有人吗？
