### ISSUE TITLE
Attempt to invoke virtual method 'void com.google.zxing.MultiFormatReader.reset()' on a null object reference

### ISSUE THREAD

**Issue by xwartz** [react-native-community/react-native-camera#1615]
### Which implementation are you using

*RNCamera*

### Crash Stacktrace
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.zxing.MultiFormatReader.reset()' on a null object reference
       at org.reactnative.camera.RNCameraView.onBarCodeScanningTaskCompleted(RNCameraView.java:290)
       at org.reactnative.camera.tasks.BarCodeScannerAsyncTask.onPostExecute(BarCodeScannerAsyncTask.java:58)
       at org.reactnative.camera.tasks.BarCodeScannerAsyncTask.onPostExecute(BarCodeScannerAsyncTask.java:10)
       at android.os.AsyncTask.finish(AsyncTask.java:660)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

### Environment
- **React Native version**:  0.51.0
- **React Native platform + platform version**: Android 5/6/7/8

### react-native-camera
**Version**: 1.1.1

**Comment by xwartz** [comment]
similar issue: https://github.com/react-native-community/react-native-camera/issues/1427

**Comment by xwartz** [comment]
I have upgraded to the latest version, and I will to see if still has this issue.

**Comment by hodatorabi** [comment]
I am having this problem and I'm currently using 1.2.0 version.
