### ISSUE TITLE
[ANDROID] - does not explicitly set microphone permissions = application crash

### ISSUE THREAD

**Issue by mcconkiee** [react-native-community/react-native-camera#1617]
We are seeing devices crash because microphone permissions are not enabled even after allowing camera permissions before starting recording. I can verify that the application is not implementing microphone permissions .

immediately after install
![screenshot_20180607-102437](https://user-images.githubusercontent.com/1483397/41116737-ff4aa07c-6a3f-11e8-96c8-10e28003ba80.png)

immediately after accepting camera permission
![screenshot_20180607-102721](https://user-images.githubusercontent.com/1483397/41116743-0214ec40-6a40-11e8-9a90-655984522371.png)

This crash only happens when we start recording

Our manifest requests the following:
```
<uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
  <uses-permission android:name="android.permission.CAMERA" />
  <uses-permission android:name="android.permission.RECORD_AUDIO"/>
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_PROFILE" />
  <uses-permission android:name="android.permission.READ_CONTACTS" />
  <uses-permission android:name="android.permission.WRITE_CONTACTS" />
```

from our component:
```
recordAVideo() {
    if (!this.camera) {
      return;
    }
    if (this.state.recording === true) {
      this.setState({ recording: false }, () => this.camera.stopRecording());
    } else {
      this.setState({ recording: true }, () =>
        this.camera
          .recordAsync({ maxDuration: 30 })
          .then(data => this.props.setVideoData(data))
          .catch(console.error));
    }
  }
// called at render()
drawCamera() {
    return (
      <RNCamera
        ref={ref => (this.camera = ref)}
        style={styles.preview}
        type={this.cameraType()}
        captureAudio
        flashMode={RNCamera.Constants.FlashMode.on}
        permissionDialogTitle="Permission to use camera"
        permissionDialogMessage="We need your permission to use your camera phone"
      >
        <DurationCounter
          recording={this.state.recording}
          onTimeout={() => this.setState({ recording: false })}
        />
        <CameraButtonRow
          savePicture={this.savePicture}
          takePicture={this.recordAVideo}
          recording={this.state.recording}
          cameraSelector={this.cameraSelector}
          cameraType={this.state.cameraType}
          onPlayback={this.playback}
          videoData={this.props.video.videoData && !this.state.recording}
        />
      </RNCamera>
    );
  }
```
error
```
Exception has occurred: Error
Error: recordAsync: Expected a Camera component
    at createErrorFromErrorData (/Users/ericmcconkie/Documents/work/BirthdayBox/Dev/birthdaybox-rn/node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:121:33)
    at /Users/ericmcconkie/Documents/work/BirthdayBox/Dev/birthdaybox-rn/node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:78:33
    at MessageQueue.__invokeCallback (/Users/ericmcconkie/Documents/work/BirthdayBox/Dev/birthdaybox-rn/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:398:5)
    at /Users/ericmcconkie/Documents/work/BirthdayBox/Dev/birthdaybox-rn/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:137:12
    at MessageQueue.__guardSafe (/Users/ericmcconkie/Documents/work/BirthdayBox/Dev/birthdaybox-rn/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:314:7)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (/Users/ericmcconkie/Documents/work/BirthdayBox/Dev/birthdaybox-rn/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:136:10)
    at /Users/ericmcconkie/Documents/work/BirthdayBox/Dev/birthdaybox-rn/.vscode/.react/debuggerWorker.js:124:58
    at process.<anonymous> (/Users/ericmcconkie/Documents/work/BirthdayBox/Dev/birthdaybox-rn/.vscode/.react/debuggerWorker.js:35:9)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
```

### Which implementation are you using

RNCamera

### Steps to reproduce
1. fresh install
2. allow permissions
3. start recording

### Expected behaviour
The application should start recording

### Actual behaviour
The application crashes until the user explicity allows microphone settings (Settings -> Apps -> AppName -> Permissions -> toggle on Microphone ). Then we get the expected behaviour

### Environment
- **React Native version**: 0.55.2
- **React Native platform + platform version**:  Android 6.0, Android 8.1 ( have not test on 7.x)

### react-native-camera
**Version**: `"react-native-camera": "^1.1.2"`

**Comment by jgfidelis** [comment]
We have this method:
```
export const requestPermissions = async (hasVideoAndAudio, CameraManager, permissionDialogTitle, permissionDialogMessage) => {
    if (Platform.OS === 'ios') {
        let check = hasVideoAndAudio
            ? CameraManager.checkDeviceAuthorizationStatus
            : CameraManager.checkVideoAuthorizationStatus;

        if (check) {
            const isAuthorized = await check();
            return isAuthorized;
        }
    } else if (Platform.OS === 'android') {
        const granted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.CAMERA, {
            title: permissionDialogTitle,
            message: permissionDialogMessage,
          });
    
          // On devices before SDK version 23, the permissions are automatically granted if they appear in the manifest,
          // so check and request should always be true.
          // https://github.com/facebook/react-native-website/blob/master/docs/permissionsandroid.md
          const isAuthorized =
            Platform.Version >= 23 ? granted === PermissionsAndroid.RESULTS.GRANTED : granted === true;
    
          return isAuthorized;
    }
    return true;
}
```

On Android we don't ask for microphone indeed.

For now, you can do a similar thing but asking for the permission of:
`PermissionsAndroid.PERMISSIONS.RECORD_AUDIO`.

And we need a pr to make something similar to the iOS version. if `hasVideoAndAudio === true`, ask for `PermissionsAndroid.PERMISSIONS.RECORD_AUDIO` as well.
