### ISSUE TITLE
Camera Crashing on S6

### ISSUE THREAD

**Issue by TylerKirby** [react-native-community/react-native-camera#1619]
### Warning
RCTCamera is **DEPRECATED** on v1.0.0 follow our [Migration guide](https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md)

### Which implementation are you using

*RNCamera*

### Steps to reproduce
1. Call `takePictureAsync` with `quality`:`1.0`

### Does it work with Expo Camera?
Check usage with Expo - https://github.com/react-native-community/react-native-camera/blob/master/docs/Expo_Usage.md
You should open an issue there as well, so we can cooperate in a solution.

### Expected behaviour
Take photo

### Actual behaviour
Crashes

### Environment
- **React Native version**: 0.52.0
- **React Native platform + platform version**: Android 7.0 (issue only occurs on Samsung Galaxy 6)

### react-native-camera
**Version**: 1.0.1

Stack trace:
```
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                 Process: com.fleettechapp, PID: 4606
                                                 java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                     at android.os.AsyncTask$3.done(AsyncTask.java:318)
                                                     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                     at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                     at java.lang.Thread.run(Thread.java:761)
                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                     at org.reactnative.camera.tasks.ResolveTakenPictureAsyncTask.doInBackground(ResolveTakenPictureAsyncTask.java:88)
                                                     at org.reactnative.camera.tasks.ResolveTakenPictureAsyncTask.doInBackground(ResolveTakenPictureAsyncTask.java:26)
                                                     at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
```

**Comment by richardkarsten** [comment]
Same Issue here on Simulator. 
Pixel 2 API 26 Android 8.0.0

**Comment by jgfidelis** [comment]
Can we close it then?

Always post issues after testing on the latest release, if possible.
