### ISSUE TITLE
[RN Camera]Android camera occasionally crashes

### ISSUE THREAD

**Issue by subugwriter** [react-native-community/react-native-camera#1894]
I am on V1.1.4.  Android camera occasionally crashes with exception:
```
    java.lang.RuntimeException: Camera is being used after Camera.release() was called
        at android.hardware.Camera.setHasPreviewCallback(Native Method)
        at android.hardware.Camera.-wrap0(Unknown Source:0)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1122)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
same as a previously closed issue: https://github.com/react-native-community/react-native-camera/issues/1357

**Comment by n1ru4l** [comment]
Please upgrade to the newest version and open an issue if you are still experiencing this crash.
