### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by amirRamirfatahi** [react-native-community/react-native-camera#1901]
# Bug Report
**To Do First**
- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Related Modules**

RNCamera
We're getting an error in our app.  
It does not occur on all android phones but it does only happen in android to my best knowledge.  
It seems like the `MultiFormatReader` is null when the `reset` method is invoked.

**Platforms**

Android

**Versions**

- Android: different versions
- react-native-camera: 1.2.0
- react-native: 0.57.0
- react: 16.5

**Description/Current Behaviour**

Attempt to invoke virtual method 'void com.google.zxing.MultiFormatReader.reset()' on a null object reference.
`
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.zxing.MultiFormatReader.reset()' on a null object reference
    at org.reactnative.camera.RNCameraView.onBarCodeScanningTaskCompleted(RNCameraView.java:294)
    at org.reactnative.camera.tasks.BarCodeScannerAsyncTask.onPostExecute(BarCodeScannerAsyncTask.java:58)
    at org.reactnative.camera.tasks.BarCodeScannerAsyncTask.onPostExecute(BarCodeScannerAsyncTask.java:10)
    at android.os.AsyncTask.finish(AsyncTask.java:695)
    at android.os.AsyncTask.-wrap1
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6938)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
`
**Steps to Reproduce**

we can't reproduce the bug.

**Comment by SimonErm** [comment]
Fixed on master.
