### ISSUE TITLE
onFacesDetected breaks app on Android (device-only)

### ISSUE THREAD

**Issue by kittisakjitmon** [react-native-community/react-native-camera#2556]
# Bug Report

To Do First

[x] Did you try latest release?
[x] Did you try master?
[x] Did you look for existing matching issues?

RNCamera

Steps to reproduce
1. Install react-native-camera with face detection using only manual procedures 
2. Import { RNCamera, FaceDetector }
3. Add component to page with onFacesDetected callback

**Actual behaviour**
The app completely crash when using onFacesDetected but when not using it working normally.
On 'IOS' can face detect 

Environment
React Native version: 0.61.2
react-native-camera version : 3.8.0

Version: npm version

*Edit
Found this error in Android Studio
```
FATAL EXCEPTION: AsyncTask #2
    Process: com.rncamera, PID: 15059
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:365)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:257)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.rncamera. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@16.0.2:240)
        at com.google.firebase.ml.vision.FirebaseVision.getInstance(Unknown Source:1)
        at org.reactnative.facedetector.RNFaceDetector.createFaceDetector(RNFaceDetector.java:95)
        at org.reactnative.facedetector.RNFaceDetector.getDetector(RNFaceDetector.java:46)
        at org.reactnative.camera.tasks.FaceDetectorAsyncTask.doInBackground(FaceDetectorAsyncTask.java:76)
        at org.reactnative.camera.tasks.FaceDetectorAsyncTask.doInBackground(FaceDetectorAsyncTask.java:22)
        at android.os.AsyncTask$2.call(AsyncTask.java:345)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:257) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:784) 
```

**Comment by KittisakChitmun** [comment]
When remove onFacesDetected line from RNCamera I working normally

**Comment by KittisakChitmun** [comment]
Repoduce
‘
react-native init test
npm install react-native-camera
‘
And follow installation doc for android step by step and then it happen this bug

**Comment by sibelius** [comment]
@KittisakChitmun without a stack trace is hard to debug

**Comment by KittisakChitmun** [comment]
Ok I will try to find its error and will return

**Comment by KittisakChitmun** [comment]
I found error in android studio 
it happen after when callback onFacesDetected
```
FATAL EXCEPTION: AsyncTask #2
    Process: com.rncamera, PID: 15059
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:365)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:257)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.rncamera. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@16.0.2:240)
        at com.google.firebase.ml.vision.FirebaseVision.getInstance(Unknown Source:1)
        at org.reactnative.facedetector.RNFaceDetector.createFaceDetector(RNFaceDetector.java:95)
        at org.reactnative.facedetector.RNFaceDetector.getDetector(RNFaceDetector.java:46)
        at org.reactnative.camera.tasks.FaceDetectorAsyncTask.doInBackground(FaceDetectorAsyncTask.java:76)
        at org.reactnative.camera.tasks.FaceDetectorAsyncTask.doInBackground(FaceDetectorAsyncTask.java:22)
        at android.os.AsyncTask$2.call(AsyncTask.java:345)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:257) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:784) 
```
