### ISSUE TITLE
Android occured

### ISSUE THREAD

**Issue by yanpeipan** [react-native-community/react-native-camera#365]
```
08-11 03:40:17.218 23174-23309/com.rn_basic E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
08-11 03:40:17.218 23174-23309/com.rn_basic E/AndroidRuntime: Process: com.rn_basic, PID: 23174
08-11 03:40:17.218 23174-23309/com.rn_basic E/AndroidRuntime: java.lang.RuntimeException: An error occured while executing doInBackground()
08-11 03:40:17.218 23174-23309/com.rn_basic E/AndroidRuntime:     at android.os.AsyncTask$3.done(AsyncTask.java:300)
08-11 03:40:17.218 23174-23309/com.rn_basic E/AndroidRuntime:     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
08-11 03:40:17.218 23174-23309/com.rn_basic E/AndroidRuntime:     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
08-11 03:40:17.218 23174-23309/com.rn_basic E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
08-11 03:40:17.218 23174-23309/com.rn_basic E/AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
08-11 03:40:17.218 23174-23309/com.rn_basic E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-11 03:40:17.218 23174-23309/com.rn_basic E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-11 03:40:17.218 23174-23309/com.rn_basic E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:818)
08-11 03:40:17.218 23174-23309/com.rn_basic E/AndroidRuntime:  Caused by: java.lang.RuntimeException: Method called after release()
08-11 03:40:17.218 23174-23309/com.rn_basic E/AndroidRuntime:     at android.hardware.Camera.setHasPreviewCallback(Native Method)
08-11 03:40:17.218 23174-23309/com.rn_basic E/AndroidRuntime:     at android.hardware.Camera.setOneShotPreviewCallback(Camera.java:850)
08-11 03:40:17.218 23174-23309/com.rn_basic E/AndroidRuntime:     at com.lwansbrough.RCTCamera.RCTCameraViewFinder.onResult(RCTCameraViewFinder.java:166)
08-11 03:40:17.218 23174-23309/com.rn_basic E/AndroidRuntime:     at com.lwansbrough.RCTCamera.BarcodeReader$ReaderAsyncTask.doInBackground(BarcodeReader.java:62)
08-11 03:40:17.218 23174-23309/com.rn_basic E/AndroidRuntime:     at com.lwansbrough.RCTCamera.BarcodeReader$ReaderAsyncTask.doInBackground(BarcodeReader.java:40)
08-11 03:40:17.218 23174-23309/com.rn_basic E/AndroidRuntime:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
08-11 03:40:17.218 23174-23309/com.rn_basic E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-11 03:40:17.218 23174-23309/com.rn_basic E/AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
08-11 03:40:17.218 23174-23309/com.rn_basic E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
08-11 03:40:17.218 23174-23309/com.rn_basic E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
08-11 03:40:17.218 23174-23309/com.rn_basic E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:818) 
```

**Comment by sabbyt54** [comment]
+1

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
