### ISSUE TITLE
java.lang.RuntimeException: Error retrieving camcorder profile params

### ISSUE THREAD

**Issue by ox-michaelradionov** [react-native-community/react-native-camera#609]
### Steps to reproduce
1. Have the following setup:
```
import Camera, { constants as CameraConstants } from 'react-native-camera';

// ...

<Camera
  aspect={CameraConstants.Aspect.fill}
  captureMode={CameraConstants.CaptureMode.video}
  captureQuality={CameraConstants.CaptureQuality['720p']}
  captureTarget={CameraConstants.CaptureTarget.temp}
  keepAwake
  ref={(cam) => { this.camera = cam; }}
  type={CameraConstants.Type.front}
/>
```

2. Call `this.camera.capture()`

### Expected behaviour
Recording should start without errors.

### Actual behaviour
Application crashes with dialog box "Unfornunatelly, AppName has stopped".

Android Studio log:

```
02-21 12:52:07.380 30155-30155/com.mindswarms E/MediaProfiles: The given camcorder profile camera 0 quality 5 is not found
02-21 12:52:07.380 30155-30155/com.mindswarms E/MediaProfiles: The given camcorder profile camera 0 quality 5 is not found
02-21 12:52:07.380 30155-30155/com.mindswarms E/MediaProfiles: The given camcorder profile camera 0 quality 5 is not found
02-21 12:52:07.380 30155-30155/com.mindswarms E/SensorManager: Exception dispatching input event.
02-21 12:52:07.380 30155-30155/com.mindswarms W/dalvikvm: JNI WARNING: JNI function SetFloatArrayRegion called with exception pending
02-21 12:52:07.380 30155-30155/com.mindswarms W/dalvikvm:              in Landroid/os/MessageQueue;.nativePollOnce:(II)V (SetFloatArrayRegion)
02-21 12:52:07.380 30155-30155/com.mindswarms W/dalvikvm: Pending exception is:
02-21 12:52:07.380 30155-30155/com.mindswarms I/dalvikvm: java.lang.RuntimeException: Error retrieving camcorder profile params
02-21 12:52:07.380 30155-30155/com.mindswarms I/dalvikvm:     at android.media.CamcorderProfile.native_get_camcorder_profile(Native Method)
02-21 12:52:07.380 30155-30155/com.mindswarms I/dalvikvm:     at android.media.CamcorderProfile.get(CamcorderProfile.java:271)
02-21 12:52:07.380 30155-30155/com.mindswarms I/dalvikvm:     at com.lwansbrough.RCTCamera.RCTCamera.setCaptureVideoQuality(RCTCamera.java:278)
02-21 12:52:07.380 30155-30155/com.mindswarms I/dalvikvm:     at com.lwansbrough.RCTCamera.RCTCameraModule.prepareMediaRecorder(RCTCameraModule.java:268)
02-21 12:52:07.380 30155-30155/com.mindswarms I/dalvikvm:     at com.lwansbrough.RCTCamera.RCTCameraModule.record(RCTCameraModule.java:354)
02-21 12:52:07.380 30155-30155/com.mindswarms I/dalvikvm:     at com.lwansbrough.RCTCamera.RCTCameraModule.captureWithOrientation(RCTCameraModule.java:641)
02-21 12:52:07.380 30155-30155/com.mindswarms I/dalvikvm:     at com.lwansbrough.RCTCamera.RCTCameraModule.access$100(RCTCameraModule.java:45)
02-21 12:52:07.380 30155-30155/com.mindswarms I/dalvikvm:     at com.lwansbrough.RCTCamera.RCTCameraModule$2.orientationEvent(RCTCameraModule.java:625)
02-21 12:52:07.380 30155-30155/com.mindswarms I/dalvikvm:     at com.lwansbrough.RCTCamera.RCTSensorOrientationChecker$Listener.onSensorChanged(RCTSensorOrientationChecker.java:64)
02-21 12:52:07.380 30155-30155/com.mindswarms I/dalvikvm:     at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:418)
02-21 12:52:07.380 30155-30155/com.mindswarms I/dalvikvm:     at android.os.MessageQueue.nativePollOnce(Native Method)
02-21 12:52:07.380 30155-30155/com.mindswarms I/dalvikvm:     at android.os.MessageQueue.next(MessageQueue.java:138)
02-21 12:52:07.380 30155-30155/com.mindswarms I/dalvikvm:     at android.os.Looper.loop(Looper.java:123)
02-21 12:52:07.380 30155-30155/com.mindswarms I/dalvikvm:     at android.app.ActivityThread.main(ActivityThread.java:5001)
02-21 12:52:07.380 30155-30155/com.mindswarms I/dalvikvm:     at java.lang.reflect.Method.invokeNative(Native Method)
02-21 12:52:07.380 30155-30155/com.mindswarms I/dalvikvm:     at java.lang.reflect.Method.invoke(Method.java:515)
02-21 12:52:07.380 30155-30155/com.mindswarms I/dalvikvm:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
02-21 12:52:07.380 30155-30155/com.mindswarms I/dalvikvm:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
02-21 12:52:07.380 30155-30155/com.mindswarms I/dalvikvm:     at dalvik.system.NativeStart.main(Native Method)
```

### Environment
- **Node.js version**: 6.5
- **React Native version**: 0.39.2
- **React Native platform + platform version**: Android 4.4
- **Device**: Asus Nexus 7 with one front camera

### react-native-camera
**Version**: 0.4.1

---

My guess is that my device (Asus Nexus 7) with one front camera does not support requested resolution of 1280x720. When I completely remove the prop `captureQuality={CameraConstants.CaptureQuality['720p']}`, recording starts fine. I would expect to have some error to be able to catch it when calling`this.camera.start` or silently defaulting to supported resolution if requested one is not supported.

**Comment by Andorbal** [comment]
I get this as well.  If someone could point me to some resources on how to test react-native module changes, I'd be willing to try and fix it.  My suggestion would be to find the next lowest available profile if the specified profile does not exist, and if there are no lower profiles available, find the next highest.

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.
