### ISSUE TITLE
stop failed: -1007

### ISSUE THREAD

**Issue by damly** [react-native-community/react-native-camera#626]
I set captureQuality={"720p"} and  get error.

E/MediaRecorder: stop failed: -1007
E/RCTCameraModule: Media recorder stop error.
                                                            java.lang.RuntimeException: stop failed.
                                                                at android.media.MediaRecorder.native_stop(Native Method)
                                                                at android.media.MediaRecorder.stop(MediaRecorder.java:1163)
                                                                at com.lwansbrough.RCTCamera.RCTCameraModule.releaseMediaRecorder(RCTCameraModule.java:400)
                                                                at com.lwansbrough.RCTCamera.RCTCameraModule.onError(RCTCameraModule.java:138)
                                                                at android.media.MediaRecorder$EventHandler.handleMessage(MediaRecorder.java:1082)
                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                at android.os.Looper.loop(Looper.java:150)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5621)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by ketanbhardwaj** [comment]
@damly I am facing the same issue. Did you find any solution?

**Comment by condorman** [comment]
@damly same error, on Android 7.0  and clean installation of react native and master version of react-native-camera. Any solution?

**Comment by arapocket** [comment]
Same error. First I was getting 'Expected a Camera component' but after adding the mute option I got this.

**Comment by watadarkstar** [comment]
I think this issue is due to re-rendering which causes the camera to re-render and stopRecording gets called. Do you call `setState` and if so where / when?

**Comment by fxcosta** [comment]
This problem is definitely state. I had a similar problem today and all because of a component that was updated within RNCamera. The solution was to put it out and modify position via "position: absolute". The strangest thing is that before this error not happen. It appeared from nowhere.

**Comment by sibelius** [comment]
RCTCamera is removed https://github.com/react-native-community/react-native-camera/issues/1890

Migrate to latest version of RNCamera
