### ISSUE TITLE
Still capture does not work on Android

### ISSUE THREAD

**Issue by dave-irvine** [react-native-community/react-native-camera#770]
Logcat shows:

```
06-28 13:55:40.956 199-20124/? I/MtkCam/Cam1Device: (20124)(Default:1)[Cam1DeviceBase::takePicture] +
06-28 13:55:40.956 199-20124/? E/MtkCam/Cam1Device: (20124)(Default:1)[Cam1DeviceBase::takePicture] NULL Camera Adapter (takePicture){#812:vendor/mediatek/proprietary/hardware/mtkcam/v1/device/Cam1DeviceBase.cpp}
06-28 13:55:40.956 20916-20916/? E/RCTCameraModule: Couldn't capture photo.
                                                    java.lang.RuntimeException: takePicture failed
                                                        at android.hardware.Camera.native_takePicture(Native Method)
                                                        at android.hardware.Camera.takePicture(Camera.java:1828)
                                                        at android.hardware.Camera.takePicture(Camera.java:1773)
                                                        at com.lwansbrough.RCTCamera.RCTCameraModule.captureWithOrientation(RCTCameraModule.java:549)
                                                        at com.lwansbrough.RCTCamera.RCTCameraModule.access$100(RCTCameraModule.java:38)
                                                        at com.lwansbrough.RCTCamera.RCTCameraModule$2.orientationEvent(RCTCameraModule.java:496)
                                                        at com.lwansbrough.RCTCamera.RCTSensorOrientationChecker$Listener.onSensorChanged(RCTSensorOrientationChecker.java:64)
                                                        at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:405)
                                                        at android.os.MessageQueue.nativePollOnce(Native Method)
                                                        at android.os.MessageQueue.next(MessageQueue.java:148)
                                                        at android.os.Looper.loop(Looper.java:151)
                                                        at android.app.ActivityThread.main(ActivityThread.java:5534)
                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
```

Not really sure what's going on here. iOS works fine.

**Comment by LitileXueZha** [comment]
i'm using at android, but the function **capture()** return nothing  as it should be Promise when i invoke then, catch,done,finally.
